const GENSER_BANK = [
  {
    "id": "g1",
    "prompt": "In Format Line 1, what does 'VZCZC' indicate?",
    "options": [
      "Start of message",
      "End of message",
      "Message precedence",
      "Classification redundancy"
    ],
    "correctIndex": 0,
    "explanation": "VZCZC indicates the start of the message (transmission identification line).",
    "tags": [
      "Line 1",
      "Transmission ID"
    ],
    "messageHtml": "<mark>VZCZC</mark>YKN001\nRTTUZYUW RHBCYKN0001 0331200-UUUU--RUDOSAB RULYCUR.\nZNR UUUUU\nR 021200Z FEB 02\nFM USS YORKTOWN\nTO USS CURTIS\nINFO SPCC MECHANICSBURG PA\nDESRON TEN\nAIG 1123\nUSS TICONDEROGA\nBT\nUNCLAS //N03207// PERSONAL FOR COMMANDING OFFICERS\nMSGID/GENADMIN/YORKTOWN/-/FEB//\nSUBJ/(U)NAVY WIDE GOLF TOURNAMENT//\nREF/A/TELCON/RADM STORM/01FEB02//\nAMPN/REF A IS A TELEPHONE CONVERSATION BETWEEN CDR KERNO AND RADM STORM IRT ALLNAV GOLF TOURNAMENT ON THE MS GULF COAST.//\nRMKS/1. IAW REF A, PLEASE DISBURSE INFORMATION TO YOUR CREWS IRT THE ALLNAV GOLF TOURNAMENT ON 14 FEB 2002. THE TOURNAMENT WILL TAKE PLACE AT PINE WOODS RESORT IN BILOXI MS, AT 1000L. HOPE TO SEE ALL THERE.//\nBT\n#0001\n\n\nNNNN"
  },
  {
    "id": "g2",
    "prompt": "In Format Line 1, what does the 3-letter group 'YKN' represent (per Lesson 4 example)?",
    "options": [
      "Station or channel designator",
      "Content Indicator Code",
      "Originating Station Routing Indicator",
      "Operating signal (OPSIG)"
    ],
    "correctIndex": 0,
    "explanation": "After VZCZC comes a 3-letter station/channel designator (YKN in the example).",
    "tags": [
      "Line 1",
      "Transmission ID"
    ],
    "messageHtml": "<mark>VZCZCYKN001</mark>\nRTTUZYUW RHBCYKN0001 0331200-UUUU--RUDOSAB RULYCUR.\nZNR UUUUU\nR 021200Z FEB 02\nFM USS YORKTOWN\nTO USS CURTIS\nINFO SPCC MECHANICSBURG PA\nDESRON TEN\nAIG 1123\nUSS TICONDEROGA\nBT\nUNCLAS //N03207// PERSONAL FOR COMMANDING OFFICERS\nMSGID/GENADMIN/YORKTOWN/-/FEB//\nSUBJ/(U)NAVY WIDE GOLF TOURNAMENT//\nREF/A/TELCON/RADM STORM/01FEB02//\nAMPN/REF A IS A TELEPHONE CONVERSATION BETWEEN CDR KERNO AND RADM STORM IRT ALLNAV GOLF TOURNAMENT ON THE MS GULF COAST.//\nRMKS/1. IAW REF A, PLEASE DISBURSE INFORMATION TO YOUR CREWS IRT THE ALLNAV GOLF TOURNAMENT ON 14 FEB 2002. THE TOURNAMENT WILL TAKE PLACE AT PINE WOODS RESORT IN BILOXI MS, AT 1000L. HOPE TO SEE ALL THERE.//\nBT\n#0001\n\n\nNNNN"
  },
  {
    "id": "g3",
    "prompt": "In the header line 'RTTUZYUW ...', what does the first character 'R' represent?",
    "options": [
      "Routine precedence",
      "Routing indicator start",
      "Restricted Data marker",
      "Radio day indicator"
    ],
    "correctIndex": 0,
    "explanation": "First character is precedence: R Routine, P Priority, O Immediate, Z Flash, Y Yankee.",
    "tags": [
      "Line 2",
      "Precedence"
    ],
    "messageHtml": "VZCZCYKN001\n<mark>RTTUZYUW</mark> RHBCYKN0001 0331200-UUUU--RUDOSAB RULYCUR.\nZNR UUUUU\nR 021200Z FEB 02\nFM USS YORKTOWN\nTO USS CURTIS\nINFO SPCC MECHANICSBURG PA\nDESRON TEN\nAIG 1123\nUSS TICONDEROGA\nBT\nUNCLAS //N03207// PERSONAL FOR COMMANDING OFFICERS\nMSGID/GENADMIN/YORKTOWN/-/FEB//\nSUBJ/(U)NAVY WIDE GOLF TOURNAMENT//\nREF/A/TELCON/RADM STORM/01FEB02//\nAMPN/REF A IS A TELEPHONE CONVERSATION BETWEEN CDR KERNO AND RADM STORM IRT ALLNAV GOLF TOURNAMENT ON THE MS GULF COAST.//\nRMKS/1. IAW REF A, PLEASE DISBURSE INFORMATION TO YOUR CREWS IRT THE ALLNAV GOLF TOURNAMENT ON 14 FEB 2002. THE TOURNAMENT WILL TAKE PLACE AT PINE WOODS RESORT IN BILOXI MS, AT 1000L. HOPE TO SEE ALL THERE.//\nBT\n#0001\n\n\nNNNN"
  },
  {
    "id": "g4",
    "prompt": "In the header line 'RTTUZYUW ...', what do characters 2–3 ('TT') represent?",
    "options": [
      "Language media format",
      "Classification",
      "Content indicator code",
      "Julian date"
    ],
    "correctIndex": 0,
    "explanation": "Characters 2–3 indicate language media format (e.g., C Card, A Automated).",
    "tags": [
      "Line 2",
      "LMF"
    ],
    "messageHtml": "VZCZCYKN001\n<mark>RTTUZYUW</mark> RHBCYKN0001 0331200-UUUU--RUDOSAB RULYCUR.\nZNR UUUUU\nR 021200Z FEB 02\nFM USS YORKTOWN\nTO USS CURTIS\nINFO SPCC MECHANICSBURG PA\nDESRON TEN\nAIG 1123\nUSS TICONDEROGA\nBT\nUNCLAS //N03207// PERSONAL FOR COMMANDING OFFICERS\nMSGID/GENADMIN/YORKTOWN/-/FEB//\nSUBJ/(U)NAVY WIDE GOLF TOURNAMENT//\nREF/A/TELCON/RADM STORM/01FEB02//\nAMPN/REF A IS A TELEPHONE CONVERSATION BETWEEN CDR KERNO AND RADM STORM IRT ALLNAV GOLF TOURNAMENT ON THE MS GULF COAST.//\nRMKS/1. IAW REF A, PLEASE DISBURSE INFORMATION TO YOUR CREWS IRT THE ALLNAV GOLF TOURNAMENT ON 14 FEB 2002. THE TOURNAMENT WILL TAKE PLACE AT PINE WOODS RESORT IN BILOXI MS, AT 1000L. HOPE TO SEE ALL THERE.//\nBT\n#0001\n\n\nNNNN"
  },
  {
    "id": "g5",
    "prompt": "In the header line 'RTTUZYUW ...', what does character 4 ('U') represent?",
    "options": [
      "Classification",
      "Precedence",
      "OPSIG",
      "OSRI"
    ],
    "correctIndex": 0,
    "explanation": "Character 4 indicates classification: U Unclass, C Confidential, S Secret, T Top Secret.",
    "tags": [
      "Line 2",
      "Classification"
    ],
    "messageHtml": "VZCZCYKN001\n<mark>RTTUZYUW</mark> RHBCYKN0001 0331200-UUUU--RUDOSAB RULYCUR.\nZNR UUUUU\nR 021200Z FEB 02\nFM USS YORKTOWN\nTO USS CURTIS\nINFO SPCC MECHANICSBURG PA\nDESRON TEN\nAIG 1123\nUSS TICONDEROGA\nBT\nUNCLAS //N03207// PERSONAL FOR COMMANDING OFFICERS\nMSGID/GENADMIN/YORKTOWN/-/FEB//\nSUBJ/(U)NAVY WIDE GOLF TOURNAMENT//\nREF/A/TELCON/RADM STORM/01FEB02//\nAMPN/REF A IS A TELEPHONE CONVERSATION BETWEEN CDR KERNO AND RADM STORM IRT ALLNAV GOLF TOURNAMENT ON THE MS GULF COAST.//\nRMKS/1. IAW REF A, PLEASE DISBURSE INFORMATION TO YOUR CREWS IRT THE ALLNAV GOLF TOURNAMENT ON 14 FEB 2002. THE TOURNAMENT WILL TAKE PLACE AT PINE WOODS RESORT IN BILOXI MS, AT 1000L. HOPE TO SEE ALL THERE.//\nBT\n#0001\n\n\nNNNN"
  },
  {
    "id": "g6",
    "prompt": "In the header line, which segment is the Content Indicator Code (CIC) in this example?",
    "options": [
      "ZYUW",
      "RHBCYKN",
      "0001",
      "033"
    ],
    "correctIndex": 0,
    "explanation": "Characters 5–8 are CIC; ZYUW indicates narrative/general text.",
    "tags": [
      "Line 2",
      "CIC"
    ],
    "messageHtml": "VZCZCYKN001\nRTTU<mark>ZYUW</mark> RHBCYKN0001 0331200-UUUU--RUDOSAB RULYCUR.\nZNR UUUUU\nR 021200Z FEB 02\nFM USS YORKTOWN\nTO USS CURTIS\nINFO SPCC MECHANICSBURG PA\nDESRON TEN\nAIG 1123\nUSS TICONDEROGA\nBT\nUNCLAS //N03207// PERSONAL FOR COMMANDING OFFICERS\nMSGID/GENADMIN/YORKTOWN/-/FEB//\nSUBJ/(U)NAVY WIDE GOLF TOURNAMENT//\nREF/A/TELCON/RADM STORM/01FEB02//\nAMPN/REF A IS A TELEPHONE CONVERSATION BETWEEN CDR KERNO AND RADM STORM IRT ALLNAV GOLF TOURNAMENT ON THE MS GULF COAST.//\nRMKS/1. IAW REF A, PLEASE DISBURSE INFORMATION TO YOUR CREWS IRT THE ALLNAV GOLF TOURNAMENT ON 14 FEB 2002. THE TOURNAMENT WILL TAKE PLACE AT PINE WOODS RESORT IN BILOXI MS, AT 1000L. HOPE TO SEE ALL THERE.//\nBT\n#0001\n\n\nNNNN"
  },
  {
    "id": "g7",
    "prompt": "Which part of the header is the Originating Station’s Routing Indicator (OSRI) in this example?",
    "options": [
      "RHBCYKN",
      "RUDOSAB",
      "0331200",
      "UUUU"
    ],
    "correctIndex": 0,
    "explanation": "Characters 10–16 are the OSRI (RHBCYKN).",
    "tags": [
      "Line 2",
      "OSRI"
    ],
    "messageHtml": "VZCZCYKN001\nRTTUZYUW <mark>RHBCYKN</mark>0001 0331200-UUUU--RUDOSAB RULYCUR.\nZNR UUUUU\nR 021200Z FEB 02\nFM USS YORKTOWN\nTO USS CURTIS\nINFO SPCC MECHANICSBURG PA\nDESRON TEN\nAIG 1123\nUSS TICONDEROGA\nBT\nUNCLAS //N03207// PERSONAL FOR COMMANDING OFFICERS\nMSGID/GENADMIN/YORKTOWN/-/FEB//\nSUBJ/(U)NAVY WIDE GOLF TOURNAMENT//\nREF/A/TELCON/RADM STORM/01FEB02//\nAMPN/REF A IS A TELEPHONE CONVERSATION BETWEEN CDR KERNO AND RADM STORM IRT ALLNAV GOLF TOURNAMENT ON THE MS GULF COAST.//\nRMKS/1. IAW REF A, PLEASE DISBURSE INFORMATION TO YOUR CREWS IRT THE ALLNAV GOLF TOURNAMENT ON 14 FEB 2002. THE TOURNAMENT WILL TAKE PLACE AT PINE WOODS RESORT IN BILOXI MS, AT 1000L. HOPE TO SEE ALL THERE.//\nBT\n#0001\n\n\nNNNN"
  },
  {
    "id": "g8",
    "prompt": "Which part of the header is the Station Serial Number (SSN) in this example?",
    "options": [
      "0001",
      "033",
      "1200",
      "UUUU"
    ],
    "correctIndex": 0,
    "explanation": "Characters 17–20 contain the SSN, a 4-digit number starting at 0001.",
    "tags": [
      "Line 2",
      "SSN"
    ],
    "messageHtml": "VZCZCYKN001\nRTTUZYUW <mark>RHBCYKN0001</mark> 0331200-UUUU--RUDOSAB RULYCUR.\nZNR UUUUU\nR 021200Z FEB 02\nFM USS YORKTOWN\nTO USS CURTIS\nINFO SPCC MECHANICSBURG PA\nDESRON TEN\nAIG 1123\nUSS TICONDEROGA\nBT\nUNCLAS //N03207// PERSONAL FOR COMMANDING OFFICERS\nMSGID/GENADMIN/YORKTOWN/-/FEB//\nSUBJ/(U)NAVY WIDE GOLF TOURNAMENT//\nREF/A/TELCON/RADM STORM/01FEB02//\nAMPN/REF A IS A TELEPHONE CONVERSATION BETWEEN CDR KERNO AND RADM STORM IRT ALLNAV GOLF TOURNAMENT ON THE MS GULF COAST.//\nRMKS/1. IAW REF A, PLEASE DISBURSE INFORMATION TO YOUR CREWS IRT THE ALLNAV GOLF TOURNAMENT ON 14 FEB 2002. THE TOURNAMENT WILL TAKE PLACE AT PINE WOODS RESORT IN BILOXI MS, AT 1000L. HOPE TO SEE ALL THERE.//\nBT\n#0001\n\n\nNNNN"
  },
  {
    "id": "g9",
    "prompt": "In the header, what does the '033' represent?",
    "options": [
      "Julian date",
      "Time filed",
      "CIC",
      "Classification redundancy"
    ],
    "correctIndex": 0,
    "explanation": "Characters 22–24 are the Julian date (001=Jan 1 … 365=Dec 31; 366 leap years).",
    "tags": [
      "Line 2",
      "Julian Date"
    ],
    "messageHtml": "VZCZCYKN001\nRTTUZYUW RHBCYKN0001 <mark>0331200</mark>-UUUU--RUDOSAB RULYCUR.\nZNR UUUUU\nR 021200Z FEB 02\nFM USS YORKTOWN\nTO USS CURTIS\nINFO SPCC MECHANICSBURG PA\nDESRON TEN\nAIG 1123\nUSS TICONDEROGA\nBT\nUNCLAS //N03207// PERSONAL FOR COMMANDING OFFICERS\nMSGID/GENADMIN/YORKTOWN/-/FEB//\nSUBJ/(U)NAVY WIDE GOLF TOURNAMENT//\nREF/A/TELCON/RADM STORM/01FEB02//\nAMPN/REF A IS A TELEPHONE CONVERSATION BETWEEN CDR KERNO AND RADM STORM IRT ALLNAV GOLF TOURNAMENT ON THE MS GULF COAST.//\nRMKS/1. IAW REF A, PLEASE DISBURSE INFORMATION TO YOUR CREWS IRT THE ALLNAV GOLF TOURNAMENT ON 14 FEB 2002. THE TOURNAMENT WILL TAKE PLACE AT PINE WOODS RESORT IN BILOXI MS, AT 1000L. HOPE TO SEE ALL THERE.//\nBT\n#0001\n\n\nNNNN"
  },
  {
    "id": "g10",
    "prompt": "In Format Line 4 'ZNR UUUUU', what does ZNR indicate?",
    "options": [
      "Unclassified message traffic OPSIG",
      "Confidential-or-higher OPSIG",
      "Break between header and body",
      "End-of-message sign"
    ],
    "correctIndex": 0,
    "explanation": "ZNR indicates unclassified message traffic. ZNY is used for confidential or higher.",
    "tags": [
      "Line 4",
      "OPSIG"
    ],
    "messageHtml": "VZCZCYKN001\nRTTUZYUW RHBCYKN0001 0331200-UUUU--RUDOSAB RULYCUR.\n<mark>ZNR UUUUU</mark>\nR 021200Z FEB 02\nFM USS YORKTOWN\nTO USS CURTIS\nINFO SPCC MECHANICSBURG PA\nDESRON TEN\nAIG 1123\nUSS TICONDEROGA\nBT\nUNCLAS //N03207// PERSONAL FOR COMMANDING OFFICERS\nMSGID/GENADMIN/YORKTOWN/-/FEB//\nSUBJ/(U)NAVY WIDE GOLF TOURNAMENT//\nREF/A/TELCON/RADM STORM/01FEB02//\nAMPN/REF A IS A TELEPHONE CONVERSATION BETWEEN CDR KERNO AND RADM STORM IRT ALLNAV GOLF TOURNAMENT ON THE MS GULF COAST.//\nRMKS/1. IAW REF A, PLEASE DISBURSE INFORMATION TO YOUR CREWS IRT THE ALLNAV GOLF TOURNAMENT ON 14 FEB 2002. THE TOURNAMENT WILL TAKE PLACE AT PINE WOODS RESORT IN BILOXI MS, AT 1000L. HOPE TO SEE ALL THERE.//\nBT\n#0001\n\n\nNNNN"
  },
  {
    "id": "g11",
    "prompt": "In Format Line 5 'R 021200Z FEB 02', which element indicates the time zone?",
    "options": [
      "Z",
      "FEB",
      "02 (year)",
      "021200 (day/hour/min)"
    ],
    "correctIndex": 0,
    "explanation": "'Z' indicates Zulu (GMT/UTC) time in DTG formatting.",
    "tags": [
      "Line 5",
      "DTG"
    ],
    "messageHtml": "VZCZCYKN001\nRTTUZYUW RHBCYKN0001 0331200-UUUU--RUDOSAB RULYCUR.\nZNR UUUUU\nR <mark>021200Z</mark> FEB 02\nFM USS YORKTOWN\nTO USS CURTIS\nINFO SPCC MECHANICSBURG PA\nDESRON TEN\nAIG 1123\nUSS TICONDEROGA\nBT\nUNCLAS //N03207// PERSONAL FOR COMMANDING OFFICERS\nMSGID/GENADMIN/YORKTOWN/-/FEB//\nSUBJ/(U)NAVY WIDE GOLF TOURNAMENT//\nREF/A/TELCON/RADM STORM/01FEB02//\nAMPN/REF A IS A TELEPHONE CONVERSATION BETWEEN CDR KERNO AND RADM STORM IRT ALLNAV GOLF TOURNAMENT ON THE MS GULF COAST.//\nRMKS/1. IAW REF A, PLEASE DISBURSE INFORMATION TO YOUR CREWS IRT THE ALLNAV GOLF TOURNAMENT ON 14 FEB 2002. THE TOURNAMENT WILL TAKE PLACE AT PINE WOODS RESORT IN BILOXI MS, AT 1000L. HOPE TO SEE ALL THERE.//\nBT\n#0001\n\n\nNNNN"
  },
  {
    "id": "g12",
    "prompt": "Which prosign identifies the originator line in a GENSER message?",
    "options": [
      "FM",
      "TO",
      "INFO",
      "XMT"
    ],
    "correctIndex": 0,
    "explanation": "Format Line 6 uses prosign FM followed by the originator PLA.",
    "tags": [
      "Line 6",
      "Originator"
    ],
    "messageHtml": "VZCZCYKN001\nRTTUZYUW RHBCYKN0001 0331200-UUUU--RUDOSAB RULYCUR.\nZNR UUUUU\nR 021200Z FEB 02\n<mark>FM USS YORKTOWN</mark>\nTO USS CURTIS\nINFO SPCC MECHANICSBURG PA\nDESRON TEN\nAIG 1123\nUSS TICONDEROGA\nBT\nUNCLAS //N03207// PERSONAL FOR COMMANDING OFFICERS\nMSGID/GENADMIN/YORKTOWN/-/FEB//\nSUBJ/(U)NAVY WIDE GOLF TOURNAMENT//\nREF/A/TELCON/RADM STORM/01FEB02//\nAMPN/REF A IS A TELEPHONE CONVERSATION BETWEEN CDR KERNO AND RADM STORM IRT ALLNAV GOLF TOURNAMENT ON THE MS GULF COAST.//\nRMKS/1. IAW REF A, PLEASE DISBURSE INFORMATION TO YOUR CREWS IRT THE ALLNAV GOLF TOURNAMENT ON 14 FEB 2002. THE TOURNAMENT WILL TAKE PLACE AT PINE WOODS RESORT IN BILOXI MS, AT 1000L. HOPE TO SEE ALL THERE.//\nBT\n#0001\n\n\nNNNN"
  },
  {
    "id": "g13",
    "prompt": "Which prosign identifies action addressees (must take action)?",
    "options": [
      "TO",
      "INFO",
      "FM",
      "BT"
    ],
    "correctIndex": 0,
    "explanation": "Format Line 7 uses TO for action addressees.",
    "tags": [
      "Line 7",
      "Action"
    ],
    "messageHtml": "VZCZCYKN001\nRTTUZYUW RHBCYKN0001 0331200-UUUU--RUDOSAB RULYCUR.\nZNR UUUUU\nR 021200Z FEB 02\nFM USS YORKTOWN\n<mark>TO USS CURTIS</mark>\nINFO SPCC MECHANICSBURG PA\nDESRON TEN\nAIG 1123\nUSS TICONDEROGA\nBT\nUNCLAS //N03207// PERSONAL FOR COMMANDING OFFICERS\nMSGID/GENADMIN/YORKTOWN/-/FEB//\nSUBJ/(U)NAVY WIDE GOLF TOURNAMENT//\nREF/A/TELCON/RADM STORM/01FEB02//\nAMPN/REF A IS A TELEPHONE CONVERSATION BETWEEN CDR KERNO AND RADM STORM IRT ALLNAV GOLF TOURNAMENT ON THE MS GULF COAST.//\nRMKS/1. IAW REF A, PLEASE DISBURSE INFORMATION TO YOUR CREWS IRT THE ALLNAV GOLF TOURNAMENT ON 14 FEB 2002. THE TOURNAMENT WILL TAKE PLACE AT PINE WOODS RESORT IN BILOXI MS, AT 1000L. HOPE TO SEE ALL THERE.//\nBT\n#0001\n\n\nNNNN"
  },
  {
    "id": "g14",
    "prompt": "Which prosign identifies information addressees (inform only)?",
    "options": [
      "INFO",
      "TO",
      "FM",
      "RMKS"
    ],
    "correctIndex": 0,
    "explanation": "Format Line 8 uses INFO for information addressees.",
    "tags": [
      "Line 8",
      "Info"
    ],
    "messageHtml": "VZCZCYKN001\nRTTUZYUW RHBCYKN0001 0331200-UUUU--RUDOSAB RULYCUR.\nZNR UUUUU\nR 021200Z FEB 02\nFM USS YORKTOWN\nTO USS CURTIS\n<mark>INFO SPCC MECHANICSBURG PA</mark>\nDESRON TEN\nAIG 1123\nUSS TICONDEROGA\nBT\nUNCLAS //N03207// PERSONAL FOR COMMANDING OFFICERS\nMSGID/GENADMIN/YORKTOWN/-/FEB//\nSUBJ/(U)NAVY WIDE GOLF TOURNAMENT//\nREF/A/TELCON/RADM STORM/01FEB02//\nAMPN/REF A IS A TELEPHONE CONVERSATION BETWEEN CDR KERNO AND RADM STORM IRT ALLNAV GOLF TOURNAMENT ON THE MS GULF COAST.//\nRMKS/1. IAW REF A, PLEASE DISBURSE INFORMATION TO YOUR CREWS IRT THE ALLNAV GOLF TOURNAMENT ON 14 FEB 2002. THE TOURNAMENT WILL TAKE PLACE AT PINE WOODS RESORT IN BILOXI MS, AT 1000L. HOPE TO SEE ALL THERE.//\nBT\n#0001\n\n\nNNNN"
  },
  {
    "id": "g15",
    "prompt": "What does the prosign 'BT' separate at the first occurrence in the message?",
    "options": [
      "Header from body",
      "Body from footer",
      "Routing indicators from OSRI",
      "DTG from originator"
    ],
    "correctIndex": 0,
    "explanation": "Format Line 11 BT separates heading (header) from the message text (body).",
    "tags": [
      "Line 11",
      "Break"
    ],
    "messageHtml": "VZCZCYKN001\nRTTUZYUW RHBCYKN0001 0331200-UUUU--RUDOSAB RULYCUR.\nZNR UUUUU\nR 021200Z FEB 02\nFM USS YORKTOWN\nTO USS CURTIS\nINFO SPCC MECHANICSBURG PA\nDESRON TEN\nAIG 1123\nUSS TICONDEROGA<mark>\nBT\nUNCLAS</mark> //N03207// PERSONAL FOR COMMANDING OFFICERS\nMSGID/GENADMIN/YORKTOWN/-/FEB//\nSUBJ/(U)NAVY WIDE GOLF TOURNAMENT//\nREF/A/TELCON/RADM STORM/01FEB02//\nAMPN/REF A IS A TELEPHONE CONVERSATION BETWEEN CDR KERNO AND RADM STORM IRT ALLNAV GOLF TOURNAMENT ON THE MS GULF COAST.//\nRMKS/1. IAW REF A, PLEASE DISBURSE INFORMATION TO YOUR CREWS IRT THE ALLNAV GOLF TOURNAMENT ON 14 FEB 2002. THE TOURNAMENT WILL TAKE PLACE AT PINE WOODS RESORT IN BILOXI MS, AT 1000L. HOPE TO SEE ALL THERE.//\nBT\n#0001\n\n\nNNNN"
  },
  {
    "id": "g16",
    "prompt": "What does the second 'BT' separate in the message?",
    "options": [
      "Body from footer",
      "Header from body",
      "Security warning from DTG",
      "CIC from OSRI"
    ],
    "correctIndex": 0,
    "explanation": "Format Line 13 BT separates the body from the footer.",
    "tags": [
      "Line 13",
      "Break"
    ],
    "messageHtml": "VZCZCYKN001\nRTTUZYUW RHBCYKN0001 0331200-UUUU--RUDOSAB RULYCUR.\nZNR UUUUU\nR 021200Z FEB 02\nFM USS YORKTOWN\nTO USS CURTIS\nINFO SPCC MECHANICSBURG PA\nDESRON TEN\nAIG 1123\nUSS TICONDEROGA\nBT\nUNCLAS //N03207// PERSONAL FOR COMMANDING OFFICERS\nMSGID/GENADMIN/YORKTOWN/-/FEB//\nSUBJ/(U)NAVY WIDE GOLF TOURNAMENT//\nREF/A/TELCON/RADM STORM/01FEB02//\nAMPN/REF A IS A TELEPHONE CONVERSATION BETWEEN CDR KERNO AND RADM STORM IRT ALLNAV GOLF TOURNAMENT ON THE MS GULF COAST.//\nRMKS/1. IAW REF A, PLEASE DISBURSE INFORMATION TO YOUR CREWS IRT THE ALLNAV GOLF TOURNAMENT ON 14 FEB 2002. THE TOURNAMENT WILL TAKE PLACE AT PINE WOODS RESORT IN BILOXI MS, AT 1000L. HOPE TO SEE ALL THERE.//<mark>\nBT\n#0001</mark>\n\n\nNNNN"
  },
  {
    "id": "g17",
    "prompt": "In the footer, what is the purpose of '#0001'?",
    "options": [
      "Validation duplicating SSN to verify completeness",
      "AIG designator for multiple addressees",
      "OPSIG for confidential traffic",
      "Julian date of message filing"
    ],
    "correctIndex": 0,
    "explanation": "Validation line duplicates the SSN preceded by '#', preventing stragglers.",
    "tags": [
      "Line 14",
      "Validation"
    ],
    "messageHtml": "VZCZCYKN001\nRTTUZYUW RHBCYKN0001 0331200-UUUU--RUDOSAB RULYCUR.\nZNR UUUUU\nR 021200Z FEB 02\nFM USS YORKTOWN\nTO USS CURTIS\nINFO SPCC MECHANICSBURG PA\nDESRON TEN\nAIG 1123\nUSS TICONDEROGA\nBT\nUNCLAS //N03207// PERSONAL FOR COMMANDING OFFICERS\nMSGID/GENADMIN/YORKTOWN/-/FEB//\nSUBJ/(U)NAVY WIDE GOLF TOURNAMENT//\nREF/A/TELCON/RADM STORM/01FEB02//\nAMPN/REF A IS A TELEPHONE CONVERSATION BETWEEN CDR KERNO AND RADM STORM IRT ALLNAV GOLF TOURNAMENT ON THE MS GULF COAST.//\nRMKS/1. IAW REF A, PLEASE DISBURSE INFORMATION TO YOUR CREWS IRT THE ALLNAV GOLF TOURNAMENT ON 14 FEB 2002. THE TOURNAMENT WILL TAKE PLACE AT PINE WOODS RESORT IN BILOXI MS, AT 1000L. HOPE TO SEE ALL THERE.//\nBT\n<mark>#0001</mark>\n\n\nNNNN"
  },
  {
    "id": "g18",
    "prompt": "What is the end-of-message sign in this format (Lesson 4)?",
    "options": [
      "NNNN",
      "VZCZC",
      "BT",
      "ZNR"
    ],
    "correctIndex": 0,
    "explanation": "End sign is NNNN (often preceded by blank lines) indicating end of message.",
    "tags": [
      "Line 16",
      "EOM"
    ],
    "messageHtml": "VZCZCYKN001\nRTTUZYUW RHBCYKN0001 0331200-UUUU--RUDOSAB RULYCUR.\nZNR UUUUU\nR 021200Z FEB 02\nFM USS YORKTOWN\nTO USS CURTIS\nINFO SPCC MECHANICSBURG PA\nDESRON TEN\nAIG 1123\nUSS TICONDEROGA\nBT\nUNCLAS //N03207// PERSONAL FOR COMMANDING OFFICERS\nMSGID/GENADMIN/YORKTOWN/-/FEB//\nSUBJ/(U)NAVY WIDE GOLF TOURNAMENT//\nREF/A/TELCON/RADM STORM/01FEB02//\nAMPN/REF A IS A TELEPHONE CONVERSATION BETWEEN CDR KERNO AND RADM STORM IRT ALLNAV GOLF TOURNAMENT ON THE MS GULF COAST.//\nRMKS/1. IAW REF A, PLEASE DISBURSE INFORMATION TO YOUR CREWS IRT THE ALLNAV GOLF TOURNAMENT ON 14 FEB 2002. THE TOURNAMENT WILL TAKE PLACE AT PINE WOODS RESORT IN BILOXI MS, AT 1000L. HOPE TO SEE ALL THERE.//\nBT\n#0001\n\n\n<mark>NNNN</mark>"
  },
  {
    "id": "g19",
    "prompt": "Which field in the body identifies the SSIC used to aid automated routing internal to a command (as described in Lesson 4)?",
    "options": [
      "The code inside the classification line (e.g., //N03207//)",
      "The SSN (e.g., 0001)",
      "The CIC (e.g., ZYUW)",
      "The OSRI (e.g., RHBCYKN)"
    ],
    "correctIndex": 0,
    "explanation": "Lesson 4: the SSIC appears within the classification/designation line (e.g., UNCLAS //N03207// ...).",
    "tags": [
      "Body",
      "SSIC"
    ],
    "messageHtml": "VZCZCYKN001\nRTTUZYUW RHBCYKN0001 0331200-UUUU--RUDOSAB RULYCUR.\nZNR UUUUU\nR 021200Z FEB 02\nFM USS YORKTOWN\nTO USS CURTIS\nINFO SPCC MECHANICSBURG PA\nDESRON TEN\nAIG 1123\nUSS TICONDEROGA\nBT\nUNCLAS <mark>//N03207//</mark> PERSONAL FOR COMMANDING OFFICERS\nMSGID/GENADMIN/YORKTOWN/-/FEB//\nSUBJ/(U)NAVY WIDE GOLF TOURNAMENT//\nREF/A/TELCON/RADM STORM/01FEB02//\nAMPN/REF A IS A TELEPHONE CONVERSATION BETWEEN CDR KERNO AND RADM STORM IRT ALLNAV GOLF TOURNAMENT ON THE MS GULF COAST.//\nRMKS/1. IAW REF A, PLEASE DISBURSE INFORMATION TO YOUR CREWS IRT THE ALLNAV GOLF TOURNAMENT ON 14 FEB 2002. THE TOURNAMENT WILL TAKE PLACE AT PINE WOODS RESORT IN BILOXI MS, AT 1000L. HOPE TO SEE ALL THERE.//\nBT\n#0001\n\n\nNNNN"
  },
  {
    "id": "g20",
    "prompt": "If a message has only one reference and that reference requires additional discussion, which field is used (Lesson 4)?",
    "options": [
      "AMPN",
      "NARR",
      "XMT",
      "OPSIG"
    ],
    "correctIndex": 0,
    "explanation": "AMPN follows a single REF set when additional discussion is needed (or TEL/CON/DOC/MSG/LTR types).",
    "tags": [
      "Body",
      "AMPN"
    ],
    "messageHtml": "VZCZCYKN001\nRTTUZYUW RHBCYKN0001 0331200-UUUU--RUDOSAB RULYCUR.\nZNR UUUUU\nR 021200Z FEB 02\nFM USS YORKTOWN\nTO USS CURTIS\nINFO SPCC MECHANICSBURG PA\nDESRON TEN\nAIG 1123\nUSS TICONDEROGA\nBT\nUNCLAS //N03207// PERSONAL FOR COMMANDING OFFICERS\nMSGID/GENADMIN/YORKTOWN/-/FEB//\nSUBJ/(U)NAVY WIDE GOLF TOURNAMENT//\nREF/A/TELCON/RADM STORM/01FEB02//\n<mark>AMPN/REF A</mark> IS A TELEPHONE CONVERSATION BETWEEN CDR KERNO AND RADM STORM IRT ALLNAV GOLF TOURNAMENT ON THE MS GULF COAST.//\nRMKS/1. IAW REF A, PLEASE DISBURSE INFORMATION TO YOUR CREWS IRT THE ALLNAV GOLF TOURNAMENT ON 14 FEB 2002. THE TOURNAMENT WILL TAKE PLACE AT PINE WOODS RESORT IN BILOXI MS, AT 1000L. HOPE TO SEE ALL THERE.//\nBT\n#0001\n\n\nNNNN"
  }
];
